// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	demoCurdFieldNames          = builder.RawFieldNames(&DemoCurd{})
	demoCurdRows                = strings.Join(demoCurdFieldNames, ",")
	demoCurdRowsExpectAutoSet   = strings.Join(stringx.Remove(demoCurdFieldNames, "`firm_id`", "`created_at`", "`deleted_at`", "`updated_at`"), ",")
	demoCurdRowsWithPlaceHolder = strings.Join(stringx.Remove(demoCurdFieldNames, "`firm_id`", "`created_at`", "`deleted_at`", "`updated_at`"), "=?,") + "=?"

	cacheVerificationSystemDemoCurdFirmIdPrefix = "cache:verificationSystem:demoCurd:firmId:"
)

type (
	demoCurdModel interface {
		Insert(ctx context.Context, data *DemoCurd) (sql.Result, error)
		FindOne(ctx context.Context, firmId int64) (*DemoCurd, error)
		Update(ctx context.Context, data *DemoCurd) error
		Delete(ctx context.Context, firmId int64) error
		Deletes(ctx context.Context, firmIds []int64) error
		FindAllByWhere(ctx context.Context, where string) ([]*DemoCurd, error)
		FindAllByWhereCount(ctx context.Context, where string) (int64, error)
		FindPageByWhere(ctx context.Context, where string, page int64, limit int64) ([]*DemoCurd, error)
		FindPageByWhereCount(ctx context.Context, where string) (int64, error)
	}

	defaultDemoCurdModel struct {
		sqlc.CachedConn
		table string
	}

	DemoCurd struct {
		FirmId    int64          `db:"firm_id"`
		FirmName  sql.NullString `db:"firm_name"`
		FirmAlias sql.NullString `db:"firm_alias"`
		FirmCode  sql.NullString `db:"firm_code"`
		FirmDesc  sql.NullString `db:"firm_desc"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
		DeletedAt sql.NullTime   `db:"deleted_at"`
	}
)

func newDemoCurdModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDemoCurdModel {
	return &defaultDemoCurdModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`demo_curd`",
	}
}

func (m *defaultDemoCurdModel) Delete(ctx context.Context, firmId int64) error {
	verificationSystemDemoCurdFirmIdKey := fmt.Sprintf("%s%v", cacheVerificationSystemDemoCurdFirmIdPrefix, firmId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		//query := fmt.Sprintf("delete from %s where `firm_id` = ?", m.table)
		query := fmt.Sprintf("update %s set `deleted_at` = now() where `firm_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, firmId)
	}, verificationSystemDemoCurdFirmIdKey)
	return err
}

func (m *defaultDemoCurdModel) Deletes(ctx context.Context, firmIds []int64) error {
	for _, firmId := range firmIds {
		verificationSystemDemoCurdFirmIdKey := fmt.Sprintf("%s%v", cacheVerificationSystemDemoCurdFirmIdPrefix, firmId)
		_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
			//query := fmt.Sprintf("delete from %s where `firm_id` = ?", m.table)
			query := fmt.Sprintf("update %s set `deleted_at` = now() where `firm_id` = ?", m.table)
			return conn.ExecCtx(ctx, query, firmId)
		}, verificationSystemDemoCurdFirmIdKey)
		if err != nil {
			return err
		}
	}

	return nil
}

func (m *defaultDemoCurdModel) FindOne(ctx context.Context, firmId int64) (*DemoCurd, error) {
	verificationSystemDemoCurdFirmIdKey := fmt.Sprintf("%s%v", cacheVerificationSystemDemoCurdFirmIdPrefix, firmId)
	var resp DemoCurd
	err := m.QueryRowCtx(ctx, &resp, verificationSystemDemoCurdFirmIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `firm_id` = ? and `deleted_at` is null  limit 1", demoCurdRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, firmId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDemoCurdModel) FindAllByWhere(ctx context.Context, where string) ([]*DemoCurd, error) {
	query := fmt.Sprintf("SELECT %s FROM %s WHERE %s ORDER BY `firm_id` DESC", demoCurdRows, m.table, where)
	var resp []*DemoCurd
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultDemoCurdModel) FindAllByWhereCount(ctx context.Context, where string) (int64, error) {
	query := fmt.Sprintf("SELECT COUNT(`firm_id`) FROM %s WHERE %s", m.table, where)
	var resp int64
	err := m.QueryRowNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultDemoCurdModel) FindPageByWhere(ctx context.Context, where string, page int64, limit int64) ([]*DemoCurd, error) {
	offset := (page - 1) * limit
	query := fmt.Sprintf("SELECT %s FROM %s WHERE %s ORDER BY `firm_id` DESC LIMIT %d,%d", demoCurdRows, m.table, where, offset, limit)
	var resp []*DemoCurd
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultDemoCurdModel) FindPageByWhereCount(ctx context.Context, where string) (int64, error) {
	query := fmt.Sprintf("SELECT COUNT(`firm_id`) FROM %s WHERE %s", m.table, where)
	var resp int64
	err := m.QueryRowNoCacheCtx(ctx, &resp, query)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultDemoCurdModel) Insert(ctx context.Context, data *DemoCurd) (sql.Result, error) {
	verificationSystemDemoCurdFirmIdKey := fmt.Sprintf("%s%v", cacheVerificationSystemDemoCurdFirmIdPrefix, data.FirmId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, demoCurdRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FirmName, data.FirmAlias, data.FirmCode, data.FirmDesc)
	}, verificationSystemDemoCurdFirmIdKey)
	return ret, err
}

func (m *defaultDemoCurdModel) Update(ctx context.Context, data *DemoCurd) error {
	verificationSystemDemoCurdFirmIdKey := fmt.Sprintf("%s%v", cacheVerificationSystemDemoCurdFirmIdPrefix, data.FirmId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `firm_id` = ?", m.table, demoCurdRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FirmName, data.FirmAlias, data.FirmCode, data.FirmDesc, data.FirmId)
	}, verificationSystemDemoCurdFirmIdKey)
	return err
}

func (m *defaultDemoCurdModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheVerificationSystemDemoCurdFirmIdPrefix, primary)
}

func (m *defaultDemoCurdModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `firm_id` = ? and `deleted_at` is null limit 1", demoCurdRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDemoCurdModel) tableName() string {
	return m.table
}
