// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	demoCurdFieldNames          = builder.RawFieldNames(&DemoCurd{})
	demoCurdRows                = strings.Join(demoCurdFieldNames, ",")
	demoCurdRowsExpectAutoSet   = strings.Join(stringx.Remove(demoCurdFieldNames, "`id`", "`created_at`", "`deleted_at`", "`updated_at`"), ",")
	demoCurdRowsWithPlaceHolder = strings.Join(stringx.Remove(demoCurdFieldNames, "`id`", "`created_at`", "`deleted_at`", "`updated_at`"), "=?,") + "=?"

	cacheZeroZoneDemoCurdIdPrefix = "cache:zeroZone:demoCurd:id:"
)

type (
	demoCurdModel interface {
		Insert(ctx context.Context, data *DemoCurd) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DemoCurd, error)
		Update(ctx context.Context, data *DemoCurd) error
		Delete(ctx context.Context, id int64) error
		Deletes(ctx context.Context, ids []int64) error
	}

	defaultDemoCurdModel struct {
		sqlc.CachedConn
		table string
	}

	DemoCurd struct {
		Id        int64          `db:"id"`
		FirmName  sql.NullString `db:"firm_name"`
		FirmAlias sql.NullString `db:"firm_alias"`
		FirmCode  sql.NullString `db:"firm_code"`
		FirmDesc  sql.NullString `db:"firm_desc"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
		DeletedAt sql.NullTime   `db:"deleted_at"`
	}
)

func newDemoCurdModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDemoCurdModel {
	return &defaultDemoCurdModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`demo_curd`",
	}
}

func (m *defaultDemoCurdModel) Delete(ctx context.Context, id int64) error {
	zeroZoneDemoCurdIdKey := fmt.Sprintf("%s%v", cacheZeroZoneDemoCurdIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		//query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		query := fmt.Sprintf("update %s set `deleted_at` = now() where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroZoneDemoCurdIdKey)
	return err
}

func (m *defaultDemoCurdModel) Deletes(ctx context.Context, ids []int64) error {
	for _, id := range ids {
		zeroZoneDemoCurdIdKey := fmt.Sprintf("%s%v", cacheZeroZoneDemoCurdIdPrefix, id)
		_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
			//query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
			query := fmt.Sprintf("update %s set `deleted_at` = now() where `id` = ?", m.table)
			return conn.ExecCtx(ctx, query, id)
		}, zeroZoneDemoCurdIdKey)
		if err != nil {
			return err
		}
	}

	return nil
}

func (m *defaultDemoCurdModel) FindOne(ctx context.Context, id int64) (*DemoCurd, error) {
	zeroZoneDemoCurdIdKey := fmt.Sprintf("%s%v", cacheZeroZoneDemoCurdIdPrefix, id)
	var resp DemoCurd
	err := m.QueryRowCtx(ctx, &resp, zeroZoneDemoCurdIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and `deleted_at` is null  limit 1", demoCurdRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDemoCurdModel) Insert(ctx context.Context, data *DemoCurd) (sql.Result, error) {
	zeroZoneDemoCurdIdKey := fmt.Sprintf("%s%v", cacheZeroZoneDemoCurdIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, demoCurdRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FirmName, data.FirmAlias, data.FirmCode, data.FirmDesc)
	}, zeroZoneDemoCurdIdKey)
	return ret, err
}

func (m *defaultDemoCurdModel) Update(ctx context.Context, data *DemoCurd) error {
	zeroZoneDemoCurdIdKey := fmt.Sprintf("%s%v", cacheZeroZoneDemoCurdIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, demoCurdRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FirmName, data.FirmAlias, data.FirmCode, data.FirmDesc, data.Id)
	}, zeroZoneDemoCurdIdKey)
	return err
}

func (m *defaultDemoCurdModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroZoneDemoCurdIdPrefix, primary)
}

func (m *defaultDemoCurdModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and `deleted_at` is null limit 1", demoCurdRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDemoCurdModel) tableName() string {
	return m.table
}
