// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallCompare(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectNew():Promise<string>;

export function SelectOld():Promise<string>;

export function SelectOldFolder():Promise<string>;
